/**
 * Seed data for all new dictionary tables.
 * Each entry has: code, label, sort_order.
 */

export const SEED_DATA: Record<string, Array<{ code: string; label: string; sort_order: number }>> = {
    dict_genders: [
        { code: 'MALE', label: 'Male', sort_order: 1 },
        { code: 'FEMALE', label: 'Female', sort_order: 2 },
        { code: 'NON_BINARY', label: 'Non-Binary', sort_order: 3 },
        { code: 'PREFER_NOT_TO_SAY', label: 'Prefer Not to Say', sort_order: 4 },
    ],

    dict_races: [
        { code: 'BLACK', label: 'Black African', sort_order: 1 },
        { code: 'COLOURED', label: 'Coloured', sort_order: 2 },
        { code: 'INDIAN', label: 'Indian / Asian', sort_order: 3 },
        { code: 'WHITE', label: 'White', sort_order: 4 },
        { code: 'OTHER', label: 'Other', sort_order: 5 },
    ],

    dict_countries: [
        { code: 'ZA', label: 'South Africa', sort_order: 1 },
        { code: 'ZW', label: 'Zimbabwe', sort_order: 2 },
        { code: 'MZ', label: 'Mozambique', sort_order: 3 },
        { code: 'NA', label: 'Namibia', sort_order: 4 },
        { code: 'BW', label: 'Botswana', sort_order: 5 },
        { code: 'LS', label: 'Lesotho', sort_order: 6 },
        { code: 'SZ', label: 'Eswatini', sort_order: 7 },
        { code: 'NG', label: 'Nigeria', sort_order: 8 },
        { code: 'GH', label: 'Ghana', sort_order: 9 },
        { code: 'KE', label: 'Kenya', sort_order: 10 },
        { code: 'UG', label: 'Uganda', sort_order: 11 },
        { code: 'CD', label: 'DR Congo', sort_order: 12 },
        { code: 'TZ', label: 'Tanzania', sort_order: 13 },
        { code: 'MW', label: 'Malawi', sort_order: 14 },
        { code: 'ZM', label: 'Zambia', sort_order: 15 },
        { code: 'AO', label: 'Angola', sort_order: 16 },
        { code: 'ET', label: 'Ethiopia', sort_order: 17 },
        { code: 'GB', label: 'United Kingdom', sort_order: 18 },
        { code: 'US', label: 'United States', sort_order: 19 },
        { code: 'IN', label: 'India', sort_order: 20 },
        { code: 'OTHER', label: 'Other', sort_order: 99 },
    ],

    dict_permit_types: [
        { code: 'WORK', label: 'Work Permit', sort_order: 1 },
        { code: 'STUDY', label: 'Study Permit', sort_order: 2 },
        { code: 'TEMPORARY_RESIDENCE', label: 'Temporary Residence', sort_order: 3 },
        { code: 'PERMANENT_RESIDENCE', label: 'Permanent Residence', sort_order: 4 },
        { code: 'REFUGEE', label: 'Refugee Status', sort_order: 5 },
        { code: 'ASYLUM', label: 'Asylum Seeker', sort_order: 6 },
        { code: 'SPOUSAL', label: 'Spousal Visa', sort_order: 7 },
        { code: 'OTHER', label: 'Other', sort_order: 99 },
    ],

    dict_typical_ages: [
        { code: 'AGE_5', label: 'Age 5 (Grade R)', sort_order: 1 },
        { code: 'AGE_6', label: 'Age 6 (Grade 1)', sort_order: 2 },
        { code: 'AGE_7', label: 'Age 7 (Grade 2)', sort_order: 3 },
        { code: 'AGE_8', label: 'Age 8 (Grade 3)', sort_order: 4 },
        { code: 'AGE_9', label: 'Age 9 (Grade 4)', sort_order: 5 },
        { code: 'AGE_10', label: 'Age 10 (Grade 5)', sort_order: 6 },
        { code: 'AGE_11', label: 'Age 11 (Grade 6)', sort_order: 7 },
        { code: 'AGE_12', label: 'Age 12 (Grade 7)', sort_order: 8 },
        { code: 'AGE_13', label: 'Age 13 (Grade 8)', sort_order: 9 },
        { code: 'AGE_14', label: 'Age 14 (Grade 9)', sort_order: 10 },
        { code: 'AGE_15', label: 'Age 15 (Grade 10)', sort_order: 11 },
        { code: 'AGE_16', label: 'Age 16 (Grade 11)', sort_order: 12 },
        { code: 'AGE_17', label: 'Age 17 (Grade 12)', sort_order: 13 },
    ],

    dict_offering_roles: [
        { code: 'COMPULSORY', label: 'Compulsory', sort_order: 1 },
        { code: 'ELECTIVE', label: 'Elective', sort_order: 2 },
        { code: 'ADDITIONAL', label: 'Additional', sort_order: 3 },
        { code: 'ENRICHMENT', label: 'Enrichment', sort_order: 4 },
    ],

    dict_selection_groups: [
        { code: 'GROUP_A', label: 'Group A — Languages', sort_order: 1 },
        { code: 'GROUP_B', label: 'Group B — Sciences', sort_order: 2 },
        { code: 'GROUP_C', label: 'Group C — Commerce', sort_order: 3 },
        { code: 'GROUP_D', label: 'Group D — Humanities', sort_order: 4 },
        { code: 'GROUP_E', label: 'Group E — Creative Arts', sort_order: 5 },
        { code: 'GROUP_F', label: 'Group F — Technology', sort_order: 6 },
    ],

    dict_extracurricular_activities: [
        { code: 'SOCCER', label: 'Soccer', sort_order: 1 },
        { code: 'RUGBY', label: 'Rugby', sort_order: 2 },
        { code: 'CRICKET', label: 'Cricket', sort_order: 3 },
        { code: 'NETBALL', label: 'Netball', sort_order: 4 },
        { code: 'HOCKEY', label: 'Hockey', sort_order: 5 },
        { code: 'TENNIS', label: 'Tennis', sort_order: 6 },
        { code: 'SWIMMING', label: 'Swimming', sort_order: 7 },
        { code: 'ATHLETICS', label: 'Athletics', sort_order: 8 },
        { code: 'CHESS', label: 'Chess', sort_order: 9 },
        { code: 'DEBATE', label: 'Debate', sort_order: 10 },
        { code: 'DRAMA', label: 'Drama', sort_order: 11 },
        { code: 'MUSIC', label: 'Music', sort_order: 12 },
        { code: 'ART', label: 'Art', sort_order: 13 },
        { code: 'DANCE', label: 'Dance', sort_order: 14 },
        { code: 'CHOIR', label: 'Choir', sort_order: 15 },
        { code: 'CODING', label: 'Coding Club', sort_order: 16 },
        { code: 'ROBOTICS', label: 'Robotics', sort_order: 17 },
        { code: 'OTHER', label: 'Other', sort_order: 99 },
    ],

    dict_parent_types: [
        { code: 'BIOLOGICAL', label: 'Biological Parent', sort_order: 1 },
        { code: 'STEP', label: 'Step-Parent', sort_order: 2 },
        { code: 'ADOPTIVE', label: 'Adoptive Parent', sort_order: 3 },
        { code: 'FOSTER', label: 'Foster Parent', sort_order: 4 },
        { code: 'GUARDIAN', label: 'Legal Guardian', sort_order: 5 },
        { code: 'GRANDPARENT', label: 'Grandparent', sort_order: 6 },
        { code: 'RELATIVE', label: 'Other Relative', sort_order: 7 },
        { code: 'OTHER', label: 'Other', sort_order: 99 },
    ],

    dict_payment_options: [
        { code: 'MONTHLY', label: 'Monthly', sort_order: 1 },
        { code: 'QUARTERLY', label: 'Quarterly', sort_order: 2 },
        { code: 'BIANNUAL', label: 'Bi-Annual', sort_order: 3 },
        { code: 'ANNUAL', label: 'Annual (upfront)', sort_order: 4 },
        { code: 'DEBIT_ORDER', label: 'Debit Order', sort_order: 5 },
    ],

    dict_employment_types: [
        { code: 'PERMANENT', label: 'Permanent', sort_order: 1 },
        { code: 'CONTRACT', label: 'Contract', sort_order: 2 },
        { code: 'TEMPORARY', label: 'Temporary', sort_order: 3 },
        { code: 'PART_TIME', label: 'Part-Time', sort_order: 4 },
        { code: 'INTERN', label: 'Intern / Student Teacher', sort_order: 5 },
        { code: 'VOLUNTEER', label: 'Volunteer', sort_order: 6 },
    ],

    // ── Master Catalog: Phases ──
    dict_phases: [
        { code: 'ECD', label: 'Early Childhood Development', sort_order: 1 },
        { code: 'PRE_GR_R', label: 'Pre-Grade R', sort_order: 2 },
        { code: 'GR_R', label: 'Grade R (Reception)', sort_order: 3 },
        { code: 'FP', label: 'Foundation Phase (Gr 1–3)', sort_order: 4 },
        { code: 'IP', label: 'Intermediate Phase (Gr 4–6)', sort_order: 5 },
        { code: 'SP', label: 'Senior Phase (Gr 7–9)', sort_order: 6 },
        { code: 'FET', label: 'FET Phase (Gr 10–12)', sort_order: 7 },
        { code: 'POST_MATRIC', label: 'Post-Matric / Gap Year', sort_order: 8 },
        { code: 'CAMBRIDGE_PRIMARY', label: 'Cambridge Primary', sort_order: 9 },
        { code: 'CAMBRIDGE_LOWER', label: 'Cambridge Lower Secondary', sort_order: 10 },
        { code: 'CAMBRIDGE_UPPER', label: 'Cambridge Upper Secondary', sort_order: 11 },
        { code: 'IB_MYP', label: 'IB Middle Years Programme', sort_order: 12 },
        { code: 'IB_DP', label: 'IB Diploma Programme', sort_order: 13 },
    ],

    // ── Master Catalog: Grades ──
    dict_grades: [
        { code: 'GR000', label: 'Grade 000 (Baby)', sort_order: 1 },
        { code: 'GR00', label: 'Grade 00 (Pre-Grade R)', sort_order: 2 },
        { code: 'GR0', label: 'Grade 0 (Grade R)', sort_order: 3 },
        { code: 'GR01', label: 'Grade 1', sort_order: 4 },
        { code: 'GR02', label: 'Grade 2', sort_order: 5 },
        { code: 'GR03', label: 'Grade 3', sort_order: 6 },
        { code: 'GR04', label: 'Grade 4', sort_order: 7 },
        { code: 'GR05', label: 'Grade 5', sort_order: 8 },
        { code: 'GR06', label: 'Grade 6', sort_order: 9 },
        { code: 'GR07', label: 'Grade 7', sort_order: 10 },
        { code: 'GR08', label: 'Grade 8', sort_order: 11 },
        { code: 'GR09', label: 'Grade 9', sort_order: 12 },
        { code: 'GR10', label: 'Grade 10', sort_order: 13 },
        { code: 'GR11', label: 'Grade 11', sort_order: 14 },
        { code: 'GR12', label: 'Grade 12', sort_order: 15 },
        { code: 'GR13', label: 'Grade 13 (Post-Matric)', sort_order: 16 },
    ],

    // ── Master Catalog: Class Genders ──
    dict_class_genders: [
        { code: 'MIXED', label: 'Mixed', sort_order: 1 },
        { code: 'MALE', label: 'Male', sort_order: 2 },
        { code: 'FEMALE', label: 'Female', sort_order: 3 },
    ],

    // ── Master Catalog: Subject Categories ──
    dict_subject_categories: [
        { code: 'LANGUAGES', label: 'Languages', sort_order: 1 },
        { code: 'MATHEMATICS', label: 'Mathematics', sort_order: 2 },
        { code: 'NATURAL_SCIENCES', label: 'Natural Sciences', sort_order: 3 },
        { code: 'TECHNOLOGY', label: 'Technology', sort_order: 4 },
        { code: 'SOCIAL_SCIENCES', label: 'Social Sciences', sort_order: 5 },
        { code: 'ECONOMIC_MANAGEMENT', label: 'Economic & Management Sciences', sort_order: 6 },
        { code: 'LIFE_SKILLS', label: 'Life Skills', sort_order: 7 },
        { code: 'ARTS_CULTURE', label: 'Arts & Culture', sort_order: 8 },
        { code: 'PHYSICAL_SCIENCE', label: 'Physical Sciences', sort_order: 9 },
        { code: 'LIFE_SCIENCES', label: 'Life Sciences', sort_order: 10 },
        { code: 'ACCOUNTING', label: 'Accounting', sort_order: 11 },
        { code: 'BUSINESS_STUDIES', label: 'Business Studies', sort_order: 12 },
        { code: 'ECONOMICS', label: 'Economics', sort_order: 13 },
        { code: 'GEOGRAPHY', label: 'Geography', sort_order: 14 },
        { code: 'HISTORY', label: 'History', sort_order: 15 },
        { code: 'COMPUTER_APPLICATIONS', label: 'Computer Applications Technology', sort_order: 16 },
        { code: 'INFORMATION_TECHNOLOGY', label: 'Information Technology', sort_order: 17 },
        { code: 'ENGINEERING_GRAPHICS', label: 'Engineering Graphics & Design', sort_order: 18 },
        { code: 'DRAMATIC_ARTS', label: 'Dramatic Arts', sort_order: 19 },
        { code: 'MUSIC', label: 'Music', sort_order: 20 },
        { code: 'VISUAL_ARTS', label: 'Visual Arts', sort_order: 21 },
        { code: 'CONSUMER_STUDIES', label: 'Consumer Studies', sort_order: 22 },
        { code: 'TOURISM', label: 'Tourism', sort_order: 23 },
        { code: 'RELIGIOUS_STUDIES', label: 'Religious Studies', sort_order: 24 },
        { code: 'AGRICULTURAL_SCIENCES', label: 'Agricultural Sciences', sort_order: 25 },
        { code: 'OTHER', label: 'Other', sort_order: 99 },
    ],

    // ── Master Catalog: Subject Types ──
    dict_subject_types: [
        { code: 'ACADEMIC', label: 'Academic', sort_order: 1 },
        { code: 'PRACTICAL', label: 'Practical', sort_order: 2 },
        { code: 'VOCATIONAL', label: 'Vocational', sort_order: 3 },
        { code: 'SPORT', label: 'Sport', sort_order: 4 },
        { code: 'CULTURAL', label: 'Cultural', sort_order: 5 },
        { code: 'EXTRACURRICULAR', label: 'Extracurricular', sort_order: 6 },
    ],

    // ── Master Catalog: Subject Language Levels ──
    dict_subject_language_levels: [
        { code: 'HL', label: 'Home Language (HL)', sort_order: 1 },
        { code: 'FAL', label: 'First Additional Language (FAL)', sort_order: 2 },
        { code: 'SAL', label: 'Second Additional Language (SAL)', sort_order: 3 },
        { code: 'NA', label: 'Not Applicable', sort_order: 4 },
    ],

    // ── Master Catalog: Home Languages (HL) ──
    dict_languages_hl: [
        { code: 'ENG', label: 'English', sort_order: 1 },
        { code: 'AFR', label: 'Afrikaans', sort_order: 2 },
        { code: 'ZUL', label: 'isiZulu', sort_order: 3 },
        { code: 'XHO', label: 'isiXhosa', sort_order: 4 },
        { code: 'SOT', label: 'Sesotho', sort_order: 5 },
        { code: 'TSN', label: 'Setswana', sort_order: 6 },
        { code: 'NSO', label: 'Sepedi (Sesotho sa Leboa)', sort_order: 7 },
        { code: 'VEN', label: 'Tshivenda', sort_order: 8 },
        { code: 'TSO', label: 'Xitsonga', sort_order: 9 },
        { code: 'SWA', label: 'siSwati', sort_order: 10 },
        { code: 'NDE', label: 'isiNdebele', sort_order: 11 },
        { code: 'SASL', label: 'South African Sign Language', sort_order: 12 },
    ],

    // ── Master Catalog: First Additional Languages (FAL) ──
    dict_languages_fal: [
        { code: 'ENG', label: 'English', sort_order: 1 },
        { code: 'AFR', label: 'Afrikaans', sort_order: 2 },
        { code: 'ZUL', label: 'isiZulu', sort_order: 3 },
        { code: 'XHO', label: 'isiXhosa', sort_order: 4 },
        { code: 'SOT', label: 'Sesotho', sort_order: 5 },
        { code: 'TSN', label: 'Setswana', sort_order: 6 },
        { code: 'NSO', label: 'Sepedi', sort_order: 7 },
        { code: 'VEN', label: 'Tshivenda', sort_order: 8 },
        { code: 'TSO', label: 'Xitsonga', sort_order: 9 },
        { code: 'SWA', label: 'siSwati', sort_order: 10 },
        { code: 'NDE', label: 'isiNdebele', sort_order: 11 },
    ],

    // ── Master Catalog: Religions ──
    dict_religions: [
        { code: 'CHRISTIANITY', label: 'Christianity', sort_order: 1 },
        { code: 'ISLAM', label: 'Islam', sort_order: 2 },
        { code: 'HINDUISM', label: 'Hinduism', sort_order: 3 },
        { code: 'JUDAISM', label: 'Judaism', sort_order: 4 },
        { code: 'BUDDHISM', label: 'Buddhism', sort_order: 5 },
        { code: 'AFRICAN_TRADITIONAL', label: 'African Traditional Religion', sort_order: 6 },
        { code: 'NONE', label: 'No Religion / Secular', sort_order: 7 },
        { code: 'OTHER', label: 'Other', sort_order: 8 },
    ],

    // ── Master Catalog: Salutations ──
    dict_salutations: [
        { code: 'MR', label: 'Mr', sort_order: 1 },
        { code: 'MRS', label: 'Mrs', sort_order: 2 },
        { code: 'MS', label: 'Ms', sort_order: 3 },
        { code: 'MISS', label: 'Miss', sort_order: 4 },
        { code: 'DR', label: 'Dr', sort_order: 5 },
        { code: 'PROF', label: 'Prof', sort_order: 6 },
        { code: 'REV', label: 'Rev', sort_order: 7 },
        { code: 'PASTOR', label: 'Pastor', sort_order: 8 },
        { code: 'BISHOP', label: 'Bishop', sort_order: 9 },
        { code: 'IMAM', label: 'Imam', sort_order: 10 },
        { code: 'SHEIKH', label: 'Sheikh', sort_order: 11 },
        { code: 'CHIEF', label: 'Chief', sort_order: 12 },
        { code: 'ADVOCATE', label: 'Adv', sort_order: 13 },
        { code: 'JUDGE', label: 'Judge', sort_order: 14 },
        { code: 'SIR', label: 'Sir', sort_order: 15 },
        { code: 'OTHER', label: 'Other', sort_order: 16 },
    ],

    // ── Master Catalog: Global Subjects ──
    dict_subjects: [
        { code: 'ENGLISH', label: 'English', sort_order: 1 },
        { code: 'AFRIKAANS', label: 'Afrikaans', sort_order: 2 },
        { code: 'ISIZULU', label: 'isiZulu', sort_order: 3 },
        { code: 'MATHEMATICS', label: 'Mathematics', sort_order: 4 },
        { code: 'MATH_LITERACY', label: 'Mathematical Literacy', sort_order: 5 },
        { code: 'TECHNICAL_MATH', label: 'Technical Mathematics', sort_order: 6 },
        { code: 'PHYSICAL_SCIENCE', label: 'Physical Sciences', sort_order: 7 },
        { code: 'LIFE_SCIENCES', label: 'Life Sciences', sort_order: 8 },
        { code: 'ACCOUNTING', label: 'Accounting', sort_order: 9 },
        { code: 'BUSINESS_STUDIES', label: 'Business Studies', sort_order: 10 },
        { code: 'ECONOMICS', label: 'Economics', sort_order: 11 },
        { code: 'GEOGRAPHY', label: 'Geography', sort_order: 12 },
        { code: 'HISTORY', label: 'History', sort_order: 13 },
        { code: 'LIFE_ORIENTATION', label: 'Life Orientation', sort_order: 14 },
        { code: 'CAT', label: 'Computer Applications Technology', sort_order: 15 },
        { code: 'IT', label: 'Information Technology', sort_order: 16 },
    ],
};
